services:
  backend:
    image: ghcr.io/maxdorninger/mediamanager/mediamanager:latest
    ports:
      - "8000:8000"
    environment:
      - CONFIG_FILE=/app/config.toml
    volumes:
      - ./data/:/data/
      - ./config.toml:/app/config.toml
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
       test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
       interval: 10s
       timeout: 5s
       retries: 5
    environment:
      POSTGRES_USER: MediaManager
      POSTGRES_DB: MediaManager
      POSTGRES_PASSWORD: MediaManager
    ports:
      - "5432:5432"


