name: Ruff
on:
  push:
    branches:
      - master
    paths:
      - 'media_manager/**'
      - 'alembic/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/python-lint.yaml'
      - 'tests/**'
  pull_request:
    paths:
      - 'media_manager/**'
      - 'alembic/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/python-lint.yaml'
      - 'tests/**'
  workflow_dispatch:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3