name: Lint Frontend

on:
  pull_request:
    paths:
      - 'web/**'
      - '.github/workflows/web-lint.yml'
  push:
    branches:
      - master
    paths:
      - 'web/**'
      - '.github/workflows/web-lint.yml'

jobs:
  lint:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: ./web
      - name: Lint code
        run: npm run lint
        working-directory: ./web

